### PR TITLE
Update to HPIncEntitlement to use REST endpoint from HPE.

### PR DESCRIPTION
**Pull request by dillten**
This merge request changes the code from the SOAP endpoint that isn't working any longer, per issue #21, to a REST endpoint that provides similar information for HPE systems. Some of the parameters used in the previous script may not apply any longer - I left them in the code but commented out. I think there are some improvements to be made here, but this is a starting framework for changing over to the new endpoint.

### CODE REVIEW

**Comment by dotps1** [comment]
Awesome!  thanks for the info, I will dig into this tonight or tomorrow morning.  Thanks again.

**Comment by dotps1** [comment]
Actually, I feel like i'm missing something, are you saying that you can use this method to lookup enterprise systems?  because the file you changed was the one for looking up workstations, and was already using a REST method to lookup.  The `Get-HPWarrantyEntilement` was the cmdlet using the SOAP request.

**Comment by dotps1** [comment]
So, I was able to get some ProdNo and SerilNo for a server, and that method does not work.  So I'm still not sure the point of this.  The orginal way the `Get-HPIncWarrantyEntitlement` is written provides more info, so I am going to leave that the way its.  If you can make this work for servers, that would be great.  thanks!

**Comment by dotps1** [comment]
maybe I spoke to soon, this did return some results for second pair lol, I was able to query a workstation using this method as well, so maybe able to converge into one cmdlet?  ill keep digging.

**Comment by dotps1** [comment]
Also, can you tell me how you came across this info?

**Comment by dillten** [comment]
No, that was my mistake, I edited the wrong script. Little transposition on my part. It was intended to modify the HPE request method.

As for the method of acquisition, I was able to find this endpoint by watching the traffic from HPE's mobile support apps.

I'll pull this back and make the modifications to the correct script.

**Pull request closed without merging**
