### PR TITLE
Add HP Inc. Entitlement Query

### PR DESCRIPTION
**Pull request by beanska**
A module and template for query HP Inc. for PC info

### CODE REVIEW

**Comment by dotps1** [comment]
so, you where able to accomplish this with out the .dll?

**Comment by beanska** [comment]
Yes, it was easier than I had assumed.

**Comment by dotps1** [comment]
awesome, I will merge this then I will prolly modify it to match the rest of the module.  please make sure you contact info is in the Authors Property in the manifest, you should get credit for this for sure!  good work!

**Comment by beanska** [comment]
Thank you for the module. I have been using it for a project to replace all PCs over age 6 in my organization. Before the script we had next to nothing. Now it pulls in warranties as part of a daily scheduled task and feeds a database where finance does predictive modeling for replacement.

**Comment by dotps1** [comment]
I have made some good progress on this, but one question I had, is in the xml template, there is a username and password, that is not your account credentials is it?

**Comment by beanska** [comment]
No, that came from using the HP Support Tool and tracing the request in
Fiddler2.

**Comment by dotps1** [comment]
works for me!

**Comment by dotps1** [comment]
i was thinking today, i wonder if they updated how the server class works as well. i need to find an HP Server.  Because right now, you have to create a registration request, then invoke the warranty lookup.  would be nice if was as easy as the workstation is now.

i hope to have everything finished tomorrow for the re design.  thanks again!

**Comment by beanska** [comment]
I just tested it with a DL785 G6 and the EIAerror is this

"Source WARRANTY SWOP 2016: This product is not eligible for HP Inc warranty; Support is obtained from Hewlett Packard Enterprise         . [TXID 6703387644]"

**Comment by dotps1** [comment]
@beanska i think HP got rid of the ISEE for the servers, and prolly went to the same method for there servers.  If you ever get a chance, you think you can run through these steps for an HP server?  see if you can atleast find the URI?  I don't have any HP servers to give it a try.  I would realy appreciate it.

Thanks!

**Pull request merged**
