### PR TITLE
Jdcarp branch

### PR DESCRIPTION
**Pull request by jdcarp**
Fixed small typo in README.

### CODE REVIEW

**Comment by jdcarp** [comment]
I hope I did this correctly, this is my first experience using Git.  Thanks!

**Comment by dotps1** [comment]
Good catch, thanks, i will re-publish my GHPage as well, it has the README embedded in it.

**Comment by dotps1** [comment]
That was mine as well.  Thanks!  have a good one!






Sent from Windows Mail





From: jdcarp
Sent: ‎Friday‎, ‎February‎ ‎20‎, ‎2015 ‎11‎:‎09‎ ‎AM
To: dotps1/HPWarranty





I hope I did this correctly, this is my first experience using Git. Thanks!

**Comment by jdcarp** [comment]
Cool!  Thanks for sharing this module.  It is great!

**Pull request merged**
