### PR TITLE
v3.0.0 Proposal

### PR DESCRIPTION
**Pull request by JustinGrote**
Hello,

I have extensively improved this module for our team's needs and am submitting these improvements for inclusion :)

1. Output as a new custom HPWarranty.HPWarrantyInfo object with a nice default table format summary, but containing complete warranty details in the object. Legacy output can be reverted by using the -AsHashTable parameter 
2. Automatic discovery of Windows and VMware ESXi SN/PN
3. Extensive and flexible pipeline support
4. Added HPSC query method in addition to ISEE method, since HP says thats the current official supported warranty info for HPE devices
5. Ability to query only serial number via HPSC method without requiring the product number
6. Comment based help added to the commands with examples.
7. Extensive error checking and -verbose output

To-Do for "3.1"
1. Make Powershell Core Compatible: Replace Invoke-WebRequest with HTML Agility Pack
2. Add PoshRSJobs to the pipeline to do parallel runspaces for query, dramatically speeding up the module for bulk queries.

### CODE REVIEW

**Comment by JustinGrote** [comment]
Whoops modulemanifest changes I made don't match your appveyor build. Will fix and resubmit

**Comment by JustinGrote** [comment]
Fixed module manifest and psm loading sequences

**Comment by JustinGrote** [comment]
Failing due to use of simple aliases such as "select" instead of "select-object". I feel they make them more readable so will resubmit with that ScriptAnalyzer Rule disabled

**Comment by JustinGrote** [comment]
This now passes Pester tests, but Appveyor build fails because you are set to publish to PSGallery every time on master, rather than with a specific deploy commit message. Upon pull acceptance it will publish correctly, but I recommend you first update your Invoke-AppveyorBuild.ps1 to only do a module publish based on a certain commit message like "!deploy", or set it to only deploy on "master" and provide me a "development" branch to send the pull request to.

Thanks.

**Comment by dotps1** [comment]
thanks for all you work on this, I haven't touched this module in quite some time.  ill review next week and get your work included.  thanks again!

**Comment by JustinGrote** [comment]
I made this core compatible but it's failing on appveyor build because it doesn't support .NET standard 2.0. I can fix this and I'll troubleshoot and build it internally and will reopen the request when it's good again.

**Comment by dotps1** [comment]
I see you closed this, do you not want it merged?  I'm just now starting to review all the changes.  Sorry its taken so long, been busy on other projects.

**Comment by JustinGrote** [comment]
I made a lot of updates, let me re-verify and I'll re-post the pull
request.

**Pull request closed without merging**
